# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.banner-mode=console
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=info
logging.level.jdbc.resultsettable=info
management.endpoints.web.exposure.include=mappings
logging.level.org.springframework=info
logging.level.org.springframework.boot.autoconfigure=info
spring.output.ansi.enabled=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/Chat
spring.datasource.username=postgres
spring.datasource.password=12345
spring.sql.init.continue-on-error=true
# spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=chatuserssecrettokentobeusedincreationofjwt
# days
jwt.expires=31

# Local Development
# server.address=192.168.137.1

# Docker Build
server.address=0.0.0.0

server.port=8080
websocket.port=8081

files.root=/app/files/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
